In [11]:
import itertools
import pandas as pd
from prediction_utils.extraction_utils.database import BQDatabase
from IPython.display import display

In [12]:
db = BQDatabase()

/local-scratch/nigam/envs/prediction_utils/lib/python3.9/site-packages/google/auth/_default.py:69: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

In [16]:
query = """
    SELECT *
    FROM som-nero-nigam-starr.spfohl_explore.{cohort_name}
"""

In [17]:
cohort_names = [
    'ascvd_starr_omop_cdm5_deid_20210130_sampled',
    'ascvd_optum_dod_2019q1_cdm_53'
]

### Basic statistics

In [18]:
cohort_names = [
    'ascvd_starr_omop_cdm5_deid_20210130_sampled'
]
group_variables = ['age_group', 'race_eth', 'gender_concept_name']
outcome_variable = 'ascvd_binary'
censored_variable = 'censored_binary'
for cohort_name in cohort_names:
    df = db.read_sql_query(query.format(cohort_name=cohort_name))
    print('Cohort Name: {cohort_name}'.format(cohort_name=cohort_name))
    print('Number of patients: {}'.format(df.shape[0]))
    display(df.groupby(['has_statin_history', 'has_cvd_history']).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))
    for group_var in group_variables:
        display(df.groupby(['has_statin_history', 'has_cvd_history', censored_variable, group_var]).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))
    for group_vars in itertools.combinations(group_variables, 2):
        display(df.query('~ascvd_binary.isnull()').groupby(['has_statin_history', 'has_cvd_history', censored_variable] + list(group_vars)).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))
    for group_vars in itertools.combinations(group_variables, 3):
        display(df.query('~ascvd_binary.isnull()').groupby(['has_statin_history', 'has_cvd_history', censored_variable] + list(group_vars)).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))

Cohort Name: ascvd_starr_omop_cdm5_deid_20210130_sampled
Number of patients: 654512

                                    incidence  num_patients
has_statin_history has_cvd_history
0                  0                 0.493852        523795
                   1                 0.950808         97728
1                  0                 0.849558         13600
                   1                 0.985064         19389

                                                              incidence  \
has_statin_history has_cvd_history censored_binary age_group
0                  0               0               [18-30)     0.235975
                                                   [30-45)     0.225632
                                                   [45-55)     0.348310
                                                   [55-65)     0.535563
                                                   [65-75)     0.709172
                                                   [75-91)     0.881383
                   1               0               [18-30)     0.908333
                                                   [30-45)     0.884228
                                                   [45-55)     0.912269
                                                   [55-65)     0.938011
                                                   [65-75)     0.961550
                                                   [75-91)     0.988851
1                  0               0               [18-30)     0.000000
                                                   [30-45)     0.428571
                                                   [45-55)     0.583333
                                                   [55-65)     0.818182
                                                   [65-75)     0.904762
                                                   [75-91)     0.968085
                   1               0               [18-30)     1.000000
                                                   [30-45)     0.934211
                                                   [45-55)     0.952381
                                                   [55-65)     0.984234
                                                   [65-75)     0.980682
                                                   [75-91)     0.996686

                                                              num_patients
has_statin_history has_cvd_history censored_binary age_group
0                  0               0               [18-30)           97342
                                                   [30-45)          143180
                                                   [45-55)           91286
                                                   [55-65)           86407
                                                   [65-75)           67602
                                                   [75-91)           37978
                   1               0               [18-30)            8308
                                                   [30-45)           11028
                                                   [45-55)           12285
                                                   [55-65)           18750
                                                   [65-75)           23790
                                                   [75-91)           23567
1                  0               0               [18-30)             104
                                                   [30-45)             799
                                                   [45-55)            2084
                                                   [55-65)            3850
                                                   [65-75)            4248
                                                   [75-91)            2515
                   1               0               [18-30)             104
                                                   [30-45)             484
                                                   [45-55)            1501
                                                   [55-65)            3618
                                                   [65-75)            6271
                                                   [75-91)            7411

                                                                              incidence  \
has_statin_history has_cvd_history censored_binary race_eth
0                  0               0               Asian                       0.495474
                                                   Black or African American   0.607477
                                                   Hispanic or Latino          0.526545
                                                   Other                       0.389230
                                                   White                       0.509474
                   1               0               Asian                       0.959540
                                                   Black or African American   0.977511
                                                   Hispanic or Latino          0.954795
                                                   Other                       0.938636
                                                   White                       0.947540
1                  0               0               Asian                       0.864407
                                                   Black or African American   0.916667
                                                   Hispanic or Latino          0.885714
                                                   Other                       0.848485
                                                   White                       0.835000
                   1               0               Asian                       0.983294
                                                   Black or African American   0.993711
                                                   Hispanic or Latino          0.986711
                                                   Other                       0.986014
                                                   White                       0.984214

                                                                              num_patients
has_statin_history has_cvd_history censored_binary race_eth
0                  0               0               Asian                             84266
                                                   Black or African American         14626
                                                   Hispanic or Latino                63617
                                                   Other                            117501
                                                   White                            243785
                   1               0               Asian                             13103
                                                   Black or African American          4206
                                                   Hispanic or Latino                11208
                                                   Other                             12762
                                                   White                             56449
1                  0               0               Asian                              2452
                                                   Black or African American           548
                                                   Hispanic or Latino                 1269
                                                   Other                              1650
                                                   White                              7681
                   1               0               Asian                              2799
                                                   Black or African American           960
                                                   Hispanic or Latino                 1774
                                                   Other                              2138
                                                   White                             11718

                                                                        incidence  \
has_statin_history has_cvd_history censored_binary gender_concept_name
0                  0               0               FEMALE                0.456622
                                                   MALE                  0.547794
                   1               0               FEMALE                0.947250
                                                   MALE                  0.954000
1                  0               0               FEMALE                0.844920
                                                   MALE                  0.855263
                   1               0               FEMALE                0.987521
                                                   MALE                  0.983230

                                                                        num_patients
has_statin_history has_cvd_history censored_binary gender_concept_name
0                  0               0               FEMALE                     315934
                                                   MALE                       207861
                   1               0               FEMALE                      47509
                                                   MALE                        50219
1                  0               0               FEMALE                       6909
                                                   MALE                         6691
                   1               0               FEMALE                       8128
                                                   MALE                        11261

                                                                                        incidence  \
has_statin_history has_cvd_history censored_binary age_group race_eth
0                  0               0               [18-30)   Asian                       0.236842
                                                             Black or African American   0.263158
                                                             Hispanic or Latino          0.321267
                                                             Other                       0.219626
                                                             White                       0.202811
...                                                                                           ...
1                  1               0               [75-91)   Asian                       1.000000
                                                             Black or African American   1.000000
                                                             Hispanic or Latino          1.000000
                                                             Other                       0.990099
                                                             White                       0.996207

                                                                                        num_patients
has_statin_history has_cvd_history censored_binary age_group race_eth
0                  0               0               [18-30)   Asian                               152
                                                             Black or African American            38
                                                             Hispanic or Latino                  221
                                                             Other                               214
                                                             White                               498
...                                                                                              ...
1                  1               0               [75-91)   Asian                               179
                                                             Black or African American            52
                                                             Hispanic or Latino                   84
                                                             Other                               101
                                                             White                               791

[115 rows x 2 columns]

                                                                                  incidence  \
has_statin_history has_cvd_history censored_binary age_group gender_concept_name
0                  0               0               [18-30)   FEMALE                0.206993
                                                             MALE                  0.286765
                                                   [30-45)   FEMALE                0.213624
                                                             MALE                  0.249198
                                                   [45-55)   FEMALE                0.334761
                                                             MALE                  0.369216
                                                   [55-65)   FEMALE                0.505296
                                                             MALE                  0.574899
                                                   [65-75)   FEMALE                0.672603
                                                             MALE                  0.752864
                                                   [75-91)   FEMALE                0.875365
                                                             MALE                  0.888628
                   1               0               [18-30)   FEMALE                0.901840
                                                             MALE                  0.916058
                                                   [30-45)   FEMALE                0.884038
                                                             MALE                  0.884532
                                                   [45-55)   FEMALE                0.908291
                                                             MALE                  0.916667
                                                   [55-65)   FEMALE                0.939980
                                                             MALE                  0.936567
                                                   [65-75)   FEMALE                0.958953
                                                             MALE                  0.963440
                                                   [75-91)   FEMALE                0.989733
                                                             MALE                  0.988062
1                  0               0               [18-30)   FEMALE                0.000000
                                                             MALE                  0.000000
                                                   [30-45)   FEMALE                0.555556
                                                             MALE                  0.200000
                                                   [45-55)   FEMALE                0.583333
                                                             MALE                  0.583333
                                                   [55-65)   FEMALE                0.800000
                                                             MALE                  0.833333
                                                   [65-75)   FEMALE                0.878788
                                                             MALE                  0.933333
                                                   [75-91)   FEMALE                0.952381
                                                             MALE                  1.000000
                   1               0               [18-30)   FEMALE                1.000000
                                                             MALE                  1.000000
                                                   [30-45)   FEMALE                0.951220
                                                             MALE                  0.914286
                                                   [45-55)   FEMALE                0.961039
                                                             MALE                  0.946429
                                                   [55-65)   FEMALE                0.988235
                                                             MALE                  0.981752
                                                   [65-75)   FEMALE                0.983380
                                                             MALE                  0.978805
                                                   [75-91)   FEMALE                0.996350
                                                             MALE                  0.996965

                                                                                  num_patients
has_statin_history has_cvd_history censored_binary age_group gender_concept_name
0                  0               0               [18-30)   FEMALE                        715
                                                             MALE                          408
                                                   [30-45)   FEMALE                       1835
                                                             MALE                          935
                                                   [45-55)   FEMALE                       1634
                                                             MALE                         1059
                                                   [55-65)   FEMALE                       1605
                                                             MALE                         1235
                                                   [65-75)   FEMALE                       1460
                                                             MALE                         1222
                                                   [75-91)   FEMALE                       1027
                                                             MALE                          853
                   1               0               [18-30)   FEMALE                        326
                                                             MALE                          274
                                                   [30-45)   FEMALE                        733
                                                             MALE                          459
                                                   [45-55)   FEMALE                        796
                                                             MALE                          720
                                                   [55-65)   FEMALE                        983
                                                             MALE                         1340
                                                   [65-75)   FEMALE                       1413
                                                             MALE                         1942
                                                   [75-91)   FEMALE                       1948
                                                             MALE                         2178
1                  0               0               [18-30)   FEMALE                          2
                                                             MALE                            2
                                                   [30-45)   FEMALE                          9
                                                             MALE                            5
                                                   [45-55)   FEMALE                         12
                                                             MALE                           12
                                                   [55-65)   FEMALE                         35
                                                             MALE                           42
                                                   [65-75)   FEMALE                         66
                                                             MALE                           60
                                                   [75-91)   FEMALE                         63
                                                             MALE                           31
                   1               0               [18-30)   FEMALE                          5
                                                             MALE                           11
                                                   [30-45)   FEMALE                         41
                                                             MALE                           35
                                                   [45-55)   FEMALE                         77
                                                             MALE                          112
                                                   [55-65)   FEMALE                        170
                                                             MALE                          274
                                                   [65-75)   FEMALE                        361
                                                             MALE                          519
                                                   [75-91)   FEMALE                        548
                                                             MALE                          659

                                                                                                  incidence  \
has_statin_history has_cvd_history censored_binary race_eth                  gender_concept_name
0                  0               0               Asian                     FEMALE                0.460692
                                                                             MALE                  0.548972
                                                   Black or African American FEMALE                0.598592
                                                                             MALE                  0.625000
                                                   Hispanic or Latino        FEMALE                0.477838
                                                                             MALE                  0.626667
                                                   Other                     FEMALE                0.362400
                                                                             MALE                  0.427912
                                                   White                     FEMALE                0.468207
                                                                             MALE                  0.564252
                   1               0               Asian                     FEMALE                0.957806
                                                                             MALE                  0.961101
                                                   Black or African American FEMALE                0.978552
                                                                             MALE                  0.976190
                                                   Hispanic or Latino        FEMALE                0.947299
                                                                             MALE                  0.962910
                                                   Other                     FEMALE                0.937400
                                                                             MALE                  0.939742
                                                   White                     FEMALE                0.942792
                                                                             MALE                  0.951524
1                  0               0               Asian                     FEMALE                0.800000
                                                                             MALE                  0.958333
                                                   Black or African American FEMALE                0.857143
                                                                             MALE                  1.000000
                                                   Hispanic or Latino        FEMALE                0.954545
                                                                             MALE                  0.769231
                                                   Other                     FEMALE                0.812500
                                                                             MALE                  0.882353
                                                   White                     FEMALE                0.841121
                                                                             MALE                  0.827957
                   1               0               Asian                     FEMALE                0.978610
                                                                             MALE                  0.987069
                                                   Black or African American FEMALE                1.000000
                                                                             MALE                  0.985294
                                                   Hispanic or Latino        FEMALE                0.993103
                                                                             MALE                  0.980769
                                                   Other                     FEMALE                0.992366
                                                                             MALE                  0.980645
                                                   White                     FEMALE                0.986111
                                                                             MALE                  0.982983

                                                                                                  num_patients
has_statin_history has_cvd_history censored_binary race_eth                  gender_concept_name
0                  0               0               Asian                     FEMALE                       1272
                                                                             MALE                          827
                                                   Black or African American FEMALE                        284
                                                                             MALE                          144
                                                   Hispanic or Latino        FEMALE                        925
                                                                             MALE                          450
                                                   Other                     FEMALE                       1250
                                                                             MALE                          867
                                                   White                     FEMALE                       4545
                                                                             MALE                         3424
                   1               0               Asian                     FEMALE                        948
                                                                             MALE                         1054
                                                   Black or African American FEMALE                        373
                                                                             MALE                          294
                                                   Hispanic or Latino        FEMALE                        759
                                                                             MALE                          701
                                                   Other                     FEMALE                        623
                                                                             MALE                          697
                                                   White                     FEMALE                       3496
                                                                             MALE                         4167
1                  0               0               Asian                     FEMALE                         35
                                                                             MALE                           24
                                                   Black or African American FEMALE                          7
                                                                             MALE                            5
                                                   Hispanic or Latino        FEMALE                         22
                                                                             MALE                           13
                                                   Other                     FEMALE                         16
                                                                             MALE                           17
                                                   White                     FEMALE                        107
                                                                             MALE                           93
                   1               0               Asian                     FEMALE                        187
                                                                             MALE                          232
                                                   Black or African American FEMALE                         91
                                                                             MALE                           68
                                                   Hispanic or Latino        FEMALE                        145
                                                                             MALE                          156
                                                   Other                     FEMALE                        131
                                                                             MALE                          155
                                                   White                     FEMALE                        648
                                                                             MALE                          999

                                                                                                            incidence  \
has_statin_history has_cvd_history censored_binary age_group race_eth                  gender_concept_name
0                  0               0               [18-30)   Asian                     FEMALE                0.189474
                                                                                       MALE                  0.315789
                                                             Black or African American FEMALE                0.321429
                                                                                       MALE                  0.100000
                                                             Hispanic or Latino        FEMALE                0.275168
...                                                                                                               ...
1                  1               0               [75-91)   Hispanic or Latino        MALE                  1.000000
                                                             Other                     FEMALE                1.000000
                                                                                       MALE                  0.979592
                                                             White                     FEMALE                0.994100
                                                                                       MALE                  0.997788

                                                                                                            num_patients
has_statin_history has_cvd_history censored_binary age_group race_eth                  gender_concept_name
0                  0               0               [18-30)   Asian                     FEMALE                         95
                                                                                       MALE                           57
                                                             Black or African American FEMALE                         28
                                                                                       MALE                           10
                                                             Hispanic or Latino        FEMALE                        149
...                                                                                                                  ...
1                  1               0               [75-91)   Hispanic or Latino        MALE                           40
                                                             Other                     FEMALE                         52
                                                                                       MALE                           49
                                                             White                     FEMALE                        339
                                                                                       MALE                          452

[227 rows x 2 columns]

In [22]:
cohort_names = [
    'ascvd_starr_omop_cdm5_deid_20210130_sampled'
]
group_variables = ['age_group', 'race_eth', 'gender_concept_name']
outcome_variable = 'ascvd_binary'
outcome_variable = 'ascvd_binary_imputed'
censored_variable = 'censored_binary'
for cohort_name in cohort_names:
    df = db.read_sql_query(query.format(cohort_name=cohort_name))
    df = df.assign(ascvd_binary_imputed=lambda x: x['ascvd_binary'].fillna(value=0))
    print('Cohort Name: {cohort_name}'.format(cohort_name=cohort_name))
    print('Number of patients: {}'.format(df.shape[0]))
    display(df.groupby(['has_statin_history', 'has_cvd_history']).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))
    for group_var in group_variables:
        display(df.groupby(['has_statin_history', 'has_cvd_history', group_var]).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))
#     for group_vars in itertools.combinations(group_variables, 2):
#         display(df.query('~ascvd_binary.isnull()').groupby(['has_statin_history', 'has_cvd_history', censored_variable] + list(group_vars)).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))
#     for group_vars in itertools.combinations(group_variables, 3):
#         display(df.query('~ascvd_binary.isnull()').groupby(['has_statin_history', 'has_cvd_history', censored_variable] + list(group_vars)).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))

Cohort Name: ascvd_starr_omop_cdm5_deid_20210130_sampled
Number of patients: 654512

                                    incidence  num_patients
has_statin_history has_cvd_history
0                  0                 0.013188        523795
                   1                 0.127568         97728
1                  0                 0.021176         13600
                   1                 0.142865         19389

                                              incidence  num_patients
has_statin_history has_cvd_history age_group
0                  0               [18-30)     0.002722         97342
                                   [30-45)     0.004365        143180
                                   [45-55)     0.010275         91286
                                   [55-65)     0.017603         86407
                                   [65-75)     0.028135         67602
                                   [75-91)     0.043631         37978
                   1               [18-30)     0.065599          8308
                                   [30-45)     0.095575         11028
                                   [45-55)     0.112576         12285
                                   [55-65)     0.116213         18750
                                   [65-75)     0.135603         23790
                                   [75-91)     0.173123         23567
1                  0               [18-30)     0.000000           104
                                   [30-45)     0.007509           799
                                   [45-55)     0.006718          2084
                                   [55-65)     0.016364          3850
                                   [65-75)     0.026836          4248
                                   [75-91)     0.036183          2515
                   1               [18-30)     0.153846           104
                                   [30-45)     0.146694           484
                                   [45-55)     0.119920          1501
                                   [55-65)     0.120785          3618
                                   [65-75)     0.137618          6271
                                   [75-91)     0.162326          7411

                                                              incidence  \
has_statin_history has_cvd_history race_eth
0                  0               Asian                       0.012342
                                   Black or African American   0.017777
                                   Hispanic or Latino          0.011381
                                   Other                       0.007013
                                   White                       0.016654
                   1               Asian                       0.146608
                                   Black or African American   0.155017
                                   Hispanic or Latino          0.124375
                                   Other                       0.097085
                                   White                       0.128629
1                  0               Asian                       0.020799
                                   Black or African American   0.020073
                                   Hispanic or Latino          0.024429
                                   Other                       0.016970
                                   White                       0.021742
                   1               Asian                       0.147195
                                   Black or African American   0.164583
                                   Hispanic or Latino          0.167418
                                   Other                       0.131899
                                   White                       0.138334

                                                              num_patients
has_statin_history has_cvd_history race_eth
0                  0               Asian                             84266
                                   Black or African American         14626
                                   Hispanic or Latino                63617
                                   Other                            117501
                                   White                            243785
                   1               Asian                             13103
                                   Black or African American          4206
                                   Hispanic or Latino                11208
                                   Other                             12762
                                   White                             56449
1                  0               Asian                              2452
                                   Black or African American           548
                                   Hispanic or Latino                 1269
                                   Other                              1650
                                   White                              7681
                   1               Asian                              2799
                                   Black or African American           960
                                   Hispanic or Latino                 1774
                                   Other                              2138
                                   White                             11718

                                                        incidence  \
has_statin_history has_cvd_history gender_concept_name
0                  0               FEMALE                0.011961
                                   MALE                  0.015053
                   1               FEMALE                0.123598
                                   MALE                  0.131325
1                  0               FEMALE                0.022869
                                   MALE                  0.019429
                   1               FEMALE                0.146038
                                   MALE                  0.140574

                                                        num_patients
has_statin_history has_cvd_history gender_concept_name
0                  0               FEMALE                     315934
                                   MALE                       207861
                   1               FEMALE                      47509
                                   MALE                        50219
1                  0               FEMALE                       6909
                                   MALE                         6691
                   1               FEMALE                       8128
                                   MALE                        11261

In [6]:
cohort_names = [
    'ascvd_starr_omop_cdm5_deid_20210130'
]
group_variables = ['age_group', 'race_eth', 'gender_concept_name']
outcome_variable = 'ascvd_binary_endpoint_censored'
censored_variable = 'endpoint_censored_binary'
for cohort_name in cohort_names:
    df = db.read_sql_query(query.format(cohort_name=cohort_name))
    print('Cohort Name: {cohort_name}'.format(cohort_name=cohort_name))
    print('Number of patients: {}'.format(df.shape[0]))
    display(df.groupby(['has_statin_history', 'has_cvd_history']).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))
    for group_var in group_variables:
        display(df.groupby(['has_statin_history', 'has_cvd_history', censored_variable, group_var]).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))
    for group_vars in itertools.combinations(group_variables, 2):
        display(df.query('~ascvd_binary.isnull()').groupby(['has_statin_history', 'has_cvd_history', censored_variable] + list(group_vars)).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))        
    for group_vars in itertools.combinations(group_variables, 3):
        display(df.query('~ascvd_binary.isnull()').groupby(['has_statin_history', 'has_cvd_history', censored_variable] + list(group_vars)).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))

Cohort Name: ascvd_starr_omop_cdm5_deid_20210130
Number of patients: 109466

                                    incidence  num_patients
has_statin_history has_cvd_history
0                  0                 0.150986         92013
                   1                 0.533633         11780
1                  0                 0.286164          2814
                   1                 0.679872          2859

                                                                       incidence  \
has_statin_history has_cvd_history endpoint_censored_binary age_group
0                  0               0                        [18-30)     0.065958
                                                            [30-45)     0.052296
                                                            [45-55)     0.089970
                                                            [55-65)     0.164600
                                                            [65-75)     0.270794
                                                            [75-91)     0.554715
                   1               0                        [18-30)     0.404092
                                                            [30-45)     0.350682
                                                            [45-55)     0.395575
                                                            [55-65)     0.450313
                                                            [65-75)     0.570142
                                                            [75-91)     0.841950
1                  0               0                        [18-30)     0.235294
                                                            [30-45)     0.077519
                                                            [45-55)     0.129338
                                                            [55-65)     0.213823
                                                            [65-75)     0.340807
                                                            [75-91)     0.683486
                   1               0                        [18-30)     0.733333
                                                            [30-45)     0.515625
                                                            [45-55)     0.492462
                                                            [55-65)     0.556338
                                                            [65-75)     0.655462
                                                            [75-91)     0.880492

                                                                       num_patients
has_statin_history has_cvd_history endpoint_censored_binary age_group
0                  0               0                        [18-30)           13752
                                                            [30-45)           22663
                                                            [45-55)           18638
                                                            [55-65)           16850
                                                            [65-75)           12088
                                                            [75-91)            8022
                   1               0                        [18-30)             793
                                                            [30-45)            1395
                                                            [45-55)            1814
                                                            [55-65)            2369
                                                            [65-75)            2545
                                                            [75-91)            2864
1                  0               0                        [18-30)              32
                                                            [30-45)             229
                                                            [45-55)             557
                                                            [55-65)             784
                                                            [65-75)             730
                                                            [75-91)             482
                   1               0                        [18-30)              19
                                                            [30-45)              90
                                                            [45-55)             289
                                                            [55-65)             638
                                                            [65-75)             851
                                                            [75-91)             972

                                                                                       incidence  \
has_statin_history has_cvd_history endpoint_censored_binary race_eth
0                  0               0                        Asian                       0.131163
                                                            Black or African American   0.217137
                                                            Hispanic or Latino          0.142763
                                                            Other                       0.102813
                                                            White                       0.165240
                   1               0                        Asian                       0.564215
                                                            Black or African American   0.642857
                                                            Hispanic or Latino          0.500000
                                                            Other                       0.493056
                                                            White                       0.532666
1                  0               0                        Asian                       0.267974
                                                            Black or African American   0.377358
                                                            Hispanic or Latino          0.311321
                                                            Other                       0.193750
                                                            White                       0.299482
                   1               0                        Asian                       0.677966
                                                            Black or African American   0.760417
                                                            Hispanic or Latino          0.707792
                                                            Other                       0.677885
                                                            White                       0.669955

                                                                                       num_patients
has_statin_history has_cvd_history endpoint_censored_binary race_eth
0                  0               0                        Asian                             12867
                                                            Black or African American          2475
                                                            Hispanic or Latino                 7690
                                                            Other                             19583
                                                            White                             49398
                   1               0                        Asian                              1500
                                                            Black or African American           392
                                                            Hispanic or Latino                 1048
                                                            Other                              1616
                                                            White                              7224
1                  0               0                        Asian                               469
                                                            Black or African American            90
                                                            Hispanic or Latino                  187
                                                            Other                               390
                                                            White                              1678
                   1               0                        Asian                               404
                                                            Black or African American           132
                                                            Hispanic or Latino                  229
                                                            Other                               367
                                                            White                              1727

                                                                                 incidence  \
has_statin_history has_cvd_history endpoint_censored_binary gender_concept_name
0                  0               0                        FEMALE                0.128838
                                                            MALE                  0.187837
                                                            No matching concept        NaN
                   1               0                        FEMALE                0.522994
                                                            MALE                  0.543157
1                  0               0                        FEMALE                0.281170
                                                            MALE                  0.291045
                   1               0                        FEMALE                0.710317
                                                            MALE                  0.659173

                                                                                 num_patients
has_statin_history has_cvd_history endpoint_censored_binary gender_concept_name
0                  0               0                        FEMALE                      55477
                                                            MALE                        36532
                                                            No matching concept             4
                   1               0                        FEMALE                       5485
                                                            MALE                         6295
1                  0               0                        FEMALE                       1366
                                                            MALE                         1448
                   1               0                        FEMALE                       1184
                                                            MALE                         1675

                                                                                                 incidence  \
has_statin_history has_cvd_history endpoint_censored_binary age_group race_eth
0                  0               0                        [18-30)   Asian                       0.044118
                                                                      Black or African American   0.108911
                                                                      Hispanic or Latino          0.088448
                                                                      Other                       0.052104
                                                                      White                       0.064833
...                                                                                                    ...
1                  1               0                        [75-91)   Asian                       0.972222
                                                                      Black or African American   1.000000
                                                                      Hispanic or Latino          1.000000
                                                                      Other                       0.933333
                                                                      White                       0.958042

                                                                                                 num_patients
has_statin_history has_cvd_history endpoint_censored_binary age_group race_eth
0                  0               0                        [18-30)   Asian                               476
                                                                      Black or African American           101
                                                                      Hispanic or Latino                  554
                                                                      Other                               499
                                                                      White                              1527
...                                                                                                       ...
1                  1               0                        [75-91)   Asian                                36
                                                                      Black or African American             7
                                                                      Hispanic or Latino                   12
                                                                      Other                                15
                                                                      White                               143

[115 rows x 2 columns]

                                                                                           incidence  \
has_statin_history has_cvd_history endpoint_censored_binary age_group gender_concept_name
0                  0               0                        [18-30)   FEMALE                0.058935
                                                                      MALE                  0.077873
                                                            [30-45)   FEMALE                0.047999
                                                                      MALE                  0.055395
                                                            [45-55)   FEMALE                0.077491
                                                                      MALE                  0.108434
                                                            [55-65)   FEMALE                0.138542
                                                                      MALE                  0.198566
                                                            [65-75)   FEMALE                0.240043
                                                                      MALE                  0.304431
                                                            [75-91)   FEMALE                0.514692
                                                                      MALE                  0.566176
                   1               0                        [18-30)   FEMALE                0.418605
                                                                      MALE                  0.398693
                                                            [30-45)   FEMALE                0.356659
                                                                      MALE                  0.365188
                                                            [45-55)   FEMALE                0.420502
                                                                      MALE                  0.413187
                                                            [55-65)   FEMALE                0.447525
                                                                      MALE                  0.490654
                                                            [65-75)   FEMALE                0.562152
                                                                      MALE                  0.615819
                                                            [75-91)   FEMALE                0.868132
                                                                      MALE                  0.847973
1                  0               0                        [18-30)   FEMALE                0.166667
                                                                      MALE                  0.000000
                                                            [30-45)   FEMALE                0.083333
                                                                      MALE                  0.125000
                                                            [45-55)   FEMALE                0.090909
                                                                      MALE                  0.115385
                                                            [55-65)   FEMALE                0.275000
                                                                      MALE                  0.380952
                                                            [65-75)   FEMALE                0.377778
                                                                      MALE                  0.515152
                                                            [75-91)   FEMALE                0.783784
                                                                      MALE                  0.850000
                   1               0                        [18-30)   FEMALE                1.000000
                                                                      MALE                  1.000000
                                                            [30-45)   FEMALE                0.600000
                                                                      MALE                  0.562500
                                                            [45-55)   FEMALE                0.730769
                                                                      MALE                  0.611111
                                                            [55-65)   FEMALE                0.787234
                                                                      MALE                  0.681818
                                                            [65-75)   FEMALE                0.802469
                                                                      MALE                  0.807692
                                                            [75-91)   FEMALE                0.980000
                                                                      MALE                  0.946903

                                                                                           num_patients
has_statin_history has_cvd_history endpoint_censored_binary age_group gender_concept_name
0                  0               0                        [18-30)   FEMALE                       2104
                                                                      MALE                         1053
                                                            [30-45)   FEMALE                       6021
                                                                      MALE                         2762
                                                            [45-55)   FEMALE                       5278
                                                                      MALE                         2905
                                                            [55-65)   FEMALE                       4403
                                                                      MALE                         2790
                                                            [65-75)   FEMALE                       2787
                                                                      MALE                         2099
                                                            [75-91)   FEMALE                       1055
                                                                      MALE                          816
                   1               0                        [18-30)   FEMALE                        215
                                                                      MALE                          153
                                                            [30-45)   FEMALE                        443
                                                                      MALE                          293
                                                            [45-55)   FEMALE                        478
                                                                      MALE                          455
                                                            [55-65)   FEMALE                        505
                                                                      MALE                          642
                                                            [65-75)   FEMALE                        539
                                                                      MALE                          708
                                                            [75-91)   FEMALE                        546
                                                                      MALE                          592
1                  0               0                        [18-30)   FEMALE                          6
                                                                      MALE                            2
                                                            [30-45)   FEMALE                         12
                                                                      MALE                            8
                                                            [45-55)   FEMALE                         22
                                                                      MALE                           26
                                                            [55-65)   FEMALE                         40
                                                                      MALE                           42
                                                            [65-75)   FEMALE                         45
                                                                      MALE                           33
                                                            [75-91)   FEMALE                         37
                                                                      MALE                           20
                   1               0                        [18-30)   FEMALE                          3
                                                                      MALE                            3
                                                            [30-45)   FEMALE                         10
                                                                      MALE                           16
                                                            [45-55)   FEMALE                         26
                                                                      MALE                           36
                                                            [55-65)   FEMALE                         47
                                                                      MALE                           88
                                                            [65-75)   FEMALE                         81
                                                                      MALE                          130
                                                            [75-91)   FEMALE                        100
                                                                      MALE                          113

                                                                                                           incidence  \
has_statin_history has_cvd_history endpoint_censored_binary race_eth                  gender_concept_name
0                  0               0                        Asian                     FEMALE                0.098765
                                                                                      MALE                  0.166667
                                                            Black or African American FEMALE                0.189769
                                                                                      MALE                  0.219672
                                                            Hispanic or Latino        FEMALE                0.122470
                                                                                      MALE                  0.171705
                                                            Other                     FEMALE                0.086926
                                                                                      MALE                  0.110112
                                                            White                     FEMALE                0.133647
                                                                                      MALE                  0.194805
                   1               0                        Asian                     FEMALE                0.571802
                                                                                      MALE                  0.602273
                                                            Black or African American FEMALE                0.620690
                                                                                      MALE                  0.702381
                                                            Hispanic or Latino        FEMALE                0.518771
                                                                                      MALE                  0.504587
                                                            Other                     FEMALE                0.455516
                                                                                      MALE                  0.540625
                                                            White                     FEMALE                0.532970
                                                                                      MALE                  0.564473
1                  0               0                        Asian                     FEMALE                0.194444
                                                                                      MALE                  0.520000
                                                            Black or African American FEMALE                0.333333
                                                                                      MALE                  0.666667
                                                            Hispanic or Latino        FEMALE                0.437500
                                                                                      MALE                  0.090909
                                                            Other                     FEMALE                0.368421
                                                                                      MALE                  0.428571
                                                            White                     FEMALE                0.447059
                                                                                      MALE                  0.410256
                   1               0                        Asian                     FEMALE                0.800000
                                                                                      MALE                  0.839286
                                                            Black or African American FEMALE                0.947368
                                                                                      MALE                  0.666667
                                                            Hispanic or Latino        FEMALE                0.923077
                                                                                      MALE                  0.625000
                                                            Other                     FEMALE                0.840000
                                                                                      MALE                  0.829268
                                                            White                     FEMALE                0.850340
                                                                                      MALE                  0.802419

                                                                                                           num_patients
has_statin_history has_cvd_history endpoint_censored_binary race_eth                  gender_concept_name
0                  0               0                        Asian                     FEMALE                       3726
                                                                                      MALE                         1890
                                                            Black or African American FEMALE                        606
                                                                                      MALE                          305
                                                            Hispanic or Latino        FEMALE                       1976
                                                                                      MALE                          827
                                                            Other                     FEMALE                       2807
                                                                                      MALE                         1780
                                                            White                     FEMALE                      12533
                                                                                      MALE                         7623
                   1               0                        Asian                     FEMALE                        383
                                                                                      MALE                          352
                                                            Black or African American FEMALE                        116
                                                                                      MALE                           84
                                                            Hispanic or Latino        FEMALE                        293
                                                                                      MALE                          218
                                                            Other                     FEMALE                        281
                                                                                      MALE                          320
                                                            White                     FEMALE                       1653
                                                                                      MALE                         1869
1                  0               0                        Asian                     FEMALE                         36
                                                                                      MALE                           25
                                                            Black or African American FEMALE                          6
                                                                                      MALE                            3
                                                            Hispanic or Latino        FEMALE                         16
                                                                                      MALE                           11
                                                            Other                     FEMALE                         19
                                                                                      MALE                           14
                                                            White                     FEMALE                         85
                                                                                      MALE                           78
                   1               0                        Asian                     FEMALE                         50
                                                                                      MALE                           56
                                                            Black or African American FEMALE                         19
                                                                                      MALE                            9
                                                            Hispanic or Latino        FEMALE                         26
                                                                                      MALE                           32
                                                            Other                     FEMALE                         25
                                                                                      MALE                           41
                                                            White                     FEMALE                        147
                                                                                      MALE                          248

In [9]:
cohort_names = [
    'ascvd_optum_dod_2019q1_cdm_53'
]
group_variables = ['age_group', 'race_eth', 'gender_concept_name']
outcome_variable = 'ascvd_binary'
censored_variable = 'censored_binary'
for cohort_name in cohort_names:
    df = db.read_sql_query(query.format(cohort_name=cohort_name))
    print('Cohort Name: {cohort_name}'.format(cohort_name=cohort_name))
    print('Number of patients: {}'.format(df.shape[0]))
    display(df.groupby(['has_statin_history', 'has_cvd_history']).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))
    for group_var in group_variables:
        display(df.groupby(['has_statin_history', 'has_cvd_history', censored_variable, group_var]).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))
    for group_vars in itertools.combinations(group_variables, 2):
        display(df.query('~ascvd_binary.isnull()').groupby(['has_statin_history', 'has_cvd_history', censored_variable] + list(group_vars)).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))
    for group_vars in itertools.combinations(group_variables, 3):
        display(df.query('~ascvd_binary.isnull()').groupby(['has_statin_history', 'has_cvd_history', censored_variable] + list(group_vars)).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))

Cohort Name: ascvd_optum_dod_2019q1_cdm_53
Number of patients: 17774872

                                    incidence  num_patients
has_statin_history has_cvd_history
0                  0                 0.246707      13451151
                   1                 0.799022       2259800
1                  0                 0.645681       1115530
                   1                 0.936252        948391

                                                              incidence  \
has_statin_history has_cvd_history censored_binary age_group
0                  0               0               [18-30)     0.047041
                                                   [30-45)     0.091000
                                                   [45-55)     0.214301
                                                   [55-65)     0.450921
                                                   [65-75)     0.639866
                                                   [75-91)     0.835959
                   1               0               [18-30)     0.253305
                                                   [30-45)     0.355861
                                                   [45-55)     0.562825
                                                   [55-65)     0.782637
                                                   [65-75)     0.873584
                                                   [75-91)     0.960049
1                  0               0               [18-30)     0.122616
                                                   [30-45)     0.241737
                                                   [45-55)     0.420181
                                                   [55-65)     0.656346
                                                   [65-75)     0.764257
                                                   [75-91)     0.892032
                   1               0               [18-30)     0.584071
                                                   [30-45)     0.684501
                                                   [45-55)     0.806657
                                                   [55-65)     0.907721
                                                   [65-75)     0.943284
                                                   [75-91)     0.980659

                                                              num_patients
has_statin_history has_cvd_history censored_binary age_group
0                  0               0               [18-30)         3335935
                                                   [30-45)         4840875
                                                   [45-55)         2807974
                                                   [55-65)         1551717
                                                   [65-75)          578367
                                                   [75-91)          336283
                   1               0               [18-30)          137605
                                                   [30-45)          379771
                                                   [45-55)          447889
                                                   [55-65)          479117
                                                   [65-75)          351406
                                                   [75-91)          464012
1                  0               0               [18-30)            9077
                                                   [30-45)          147468
                                                   [45-55)          297008
                                                   [55-65)          340663
                                                   [65-75)          204705
                                                   [75-91)          116609
                   1               0               [18-30)            1616
                                                   [30-45)           41814
                                                   [45-55)          140053
                                                   [55-65)          258838
                                                   [65-75)          246433
                                                   [75-91)          259637

                                                                              incidence  \
has_statin_history has_cvd_history censored_binary race_eth
0                  0               0               Asian                       0.178394
                                                   Black or African American   0.272703
                                                   Hispanic or Latino          0.224891
                                                   Other                       0.401470
                                                   White                       0.239764
                   1               0               Asian                       0.720445
                                                   Black or African American   0.802458
                                                   Hispanic or Latino          0.729502
                                                   Other                       0.888426
                                                   White                       0.798737
1                  0               0               Asian                       0.604181
                                                   Black or African American   0.654066
                                                   Hispanic or Latino          0.637873
                                                   Other                       0.752233
                                                   White                       0.638072
                   1               0               Asian                       0.926269
                                                   Black or African American   0.939330
                                                   Hispanic or Latino          0.915750
                                                   Other                       0.959992
                                                   White                       0.936146

                                                                              num_patients
has_statin_history has_cvd_history censored_binary race_eth
0                  0               0               Asian                            494373
                                                   Black or African American       1030987
                                                   Hispanic or Latino              1199953
                                                   Other                           2200795
                                                   White                           8525043
                   1               0               Asian                             55199
                                                   Black or African American        226561
                                                   Hispanic or Latino               173736
                                                   Other                            283226
                                                   White                           1521078
1                  0               0               Asian                             36369
                                                   Black or African American         87412
                                                   Hispanic or Latino               113247
                                                   Other                            133378
                                                   White                            745124
                   1               0               Asian                             21325
                                                   Black or African American         92667
                                                   Hispanic or Latino                83450
                                                   Other                             92513
                                                   White                            658436

                                                                        incidence  \
has_statin_history has_cvd_history censored_binary gender_concept_name
0                  0               0               FEMALE                0.247287
                                                   MALE                  0.245854
                                                   No matching concept   0.800000
                   1               0               FEMALE                0.791571
                                                   MALE                  0.807391
                                                   No matching concept   0.963855
1                  0               0               FEMALE                0.686324
                                                   MALE                  0.599391
                                                   No matching concept   1.000000
                   1               0               FEMALE                0.941335
                                                   MALE                  0.931481
                                                   No matching concept   0.960000

                                                                        num_patients
has_statin_history has_cvd_history censored_binary gender_concept_name
0                  0               0               FEMALE                    7544055
                                                   MALE                      5904876
                                                   No matching concept          2220
                   1               0               FEMALE                    1205480
                                                   MALE                      1053846
                                                   No matching concept           474
1                  0               0               FEMALE                     547532
                                                   MALE                       567836
                                                   No matching concept           162
                   1               0               FEMALE                     429134
                                                   MALE                       519074
                                                   No matching concept           183

                                                                                        incidence  \
has_statin_history has_cvd_history censored_binary age_group race_eth
0                  0               0               [18-30)   Asian                       0.037321
                                                             Black or African American   0.056122
                                                             Hispanic or Latino          0.052327
                                                             Other                       0.120132
                                                             White                       0.041884
...                                                                                           ...
1                  1               0               [75-91)   Asian                       0.979511
                                                             Black or African American   0.981585
                                                             Hispanic or Latino          0.967263
                                                             Other                       0.986104
                                                             White                       0.981799

                                                                                        num_patients
has_statin_history has_cvd_history censored_binary age_group race_eth
0                  0               0               [18-30)   Asian                             12111
                                                             Black or African American         28349
                                                             Hispanic or Latino                37094
                                                             Other                             12095
                                                             White                            236512
...                                                                                              ...
1                  1               0               [75-91)   Asian                              1269
                                                             Black or African American          5213
                                                             Hispanic or Latino                 5590
                                                             Other                              4102
                                                             White                             43130

[120 rows x 2 columns]

                                                                                  incidence  \
has_statin_history has_cvd_history censored_binary age_group gender_concept_name
0                  0               0               [18-30)   FEMALE                0.048495
                                                             MALE                  0.045218
                                                             No matching concept   0.000000
                                                   [30-45)   FEMALE                0.093373
                                                             MALE                  0.088053
...                                                                                     ...
1                  1               0               [65-75)   MALE                  0.946690
                                                             No matching concept   1.000000
                                                   [75-91)   FEMALE                0.978620
                                                             MALE                  0.983119
                                                             No matching concept   1.000000

                                                                                  num_patients
has_statin_history has_cvd_history censored_binary age_group gender_concept_name
0                  0               0               [18-30)   FEMALE                     181502
                                                             MALE                       144656
                                                             No matching concept             3
                                                   [30-45)   FEMALE                     336919
                                                             MALE                       276595
...                                                                                        ...
1                  1               0               [65-75)   MALE                        19002
                                                             No matching concept             7
                                                   [75-91)   FEMALE                      32461
                                                             MALE                        26835
                                                             No matching concept             8

[67 rows x 2 columns]

                                                                                                  incidence  \
has_statin_history has_cvd_history censored_binary race_eth                  gender_concept_name
0                  0               0               Asian                     FEMALE                0.169906
                                                                             MALE                  0.188644
                                                                             No matching concept   0.666667
                                                   Black or African American FEMALE                0.270227
                                                                             MALE                  0.276084
                                                                             No matching concept   0.833333
                                                   Hispanic or Latino        FEMALE                0.223693
                                                                             MALE                  0.226359
                                                                             No matching concept   1.000000
                                                   Other                     FEMALE                0.418936
                                                                             MALE                  0.376757
                                                                             No matching concept   0.787234
                                                   White                     FEMALE                0.239392
                                                                             MALE                  0.240133
                                                                             No matching concept   0.790698
                   1               0               Asian                     FEMALE                0.711401
                                                                             MALE                  0.729010
                                                                             No matching concept   1.000000
                                                   Black or African American FEMALE                0.794345
                                                                             MALE                  0.813708
                                                                             No matching concept   0.968750
                                                   Hispanic or Latino        FEMALE                0.716156
                                                                             MALE                  0.744915
                                                                             No matching concept   0.800000
                                                   Other                     FEMALE                0.892906
                                                                             MALE                  0.882328
                                                                             No matching concept   0.914286
                                                   White                     FEMALE                0.789771
                                                                             MALE                  0.808380
                                                                             No matching concept   0.989011
1                  0               0               Asian                     FEMALE                0.656672
                                                                             MALE                  0.560736
                                                                             No matching concept   1.000000
                                                   Black or African American FEMALE                0.691819
                                                                             MALE                  0.600241
                                                                             No matching concept   1.000000
                                                   Hispanic or Latino        FEMALE                0.670902
                                                                             MALE                  0.600145
                                                   Other                     FEMALE                0.790925
                                                                             MALE                  0.699454
                                                                             No matching concept   1.000000
                                                   White                     FEMALE                0.678918
                                                                             MALE                  0.592929
                                                                             No matching concept   1.000000
                   1               0               Asian                     FEMALE                0.937991
                                                                             MALE                  0.917579
                                                                             No matching concept   1.000000
                                                   Black or African American FEMALE                0.940655
                                                                             MALE                  0.937583
                                                                             No matching concept   1.000000
                                                   Hispanic or Latino        FEMALE                0.915762
                                                                             MALE                  0.915738
                                                   Other                     FEMALE                0.966008
                                                                             MALE                  0.953508
                                                                             No matching concept   0.857143
                                                   White                     FEMALE                0.941913
                                                                             MALE                  0.931011
                                                                             No matching concept   1.000000

                                                                                                  num_patients
has_statin_history has_cvd_history censored_binary race_eth                  gender_concept_name
0                  0               0               Asian                     FEMALE                      34160
                                                                             MALE                        28143
                                                                             No matching concept             3
                                                   Black or African American FEMALE                      91401
                                                                             MALE                        59960
                                                                             No matching concept            42
                                                   Hispanic or Latino        FEMALE                      92685
                                                                             MALE                        74541
                                                                             No matching concept             2
                                                   Other                     FEMALE                      48184
                                                                             MALE                        34789
                                                                             No matching concept            47
                                                   White                     FEMALE                     701359
                                                                             MALE                       577504
                                                                             No matching concept            86
                   1               0               Asian                     FEMALE                       7131
                                                                             MALE                         7432
                                                                             No matching concept             3
                                                   Black or African American FEMALE                      41910
                                                                             MALE                        29749
                                                                             No matching concept            32
                                                   Hispanic or Latino        FEMALE                      25972
                                                                             MALE                        22467
                                                                             No matching concept             5
                                                   Other                     FEMALE                      28293
                                                                             MALE                        20931
                                                                             No matching concept            35
                                                   White                     FEMALE                     251659
                                                                             MALE                       232163
                                                                             No matching concept            91
1                  0               0               Asian                     FEMALE                        667
                                                                             MALE                          815
                                                                             No matching concept             1
                                                   Black or African American FEMALE                       2359
                                                                             MALE                         1661
                                                                             No matching concept             1
                                                   Hispanic or Latino        FEMALE                       3148
                                                                             MALE                         2756
                                                   Other                     FEMALE                       1741
                                                                             MALE                         1281
                                                                             No matching concept             1
                                                   White                     FEMALE                      17114
                                                                             MALE                        15501
                                                                             No matching concept             2
                   1               0               Asian                     FEMALE                       1145
                                                                             MALE                         1553
                                                                             No matching concept             1
                                                   Black or African American FEMALE                       7667
                                                                             MALE                         6056
                                                                             No matching concept             7
                                                   Hispanic or Latino        FEMALE                       5710
                                                                             MALE                         6195
                                                   Other                     FEMALE                       5266
                                                                             MALE                         4775
                                                                             No matching concept             7
                                                   White                     FEMALE                      43521
                                                                             MALE                        49008
                                                                             No matching concept            10

                                                                                                            incidence  \
has_statin_history has_cvd_history censored_binary age_group race_eth                  gender_concept_name
0                  0               0               [18-30)   Asian                     FEMALE                0.036215
                                                                                       MALE                  0.038829
                                                             Black or African American FEMALE                0.058407
                                                                                       MALE                  0.052341
                                                             Hispanic or Latino        FEMALE                0.053809
...                                                                                                               ...
1                  1               0               [75-91)   Other                     FEMALE                0.985709
                                                                                       MALE                  0.986890
                                                             White                     FEMALE                0.979751
                                                                                       MALE                  0.984118
                                                                                       No matching concept   1.000000

                                                                                                            num_patients
has_statin_history has_cvd_history censored_binary age_group race_eth                  gender_concept_name
0                  0               0               [18-30)   Asian                     FEMALE                       6986
                                                                                       MALE                         5125
                                                             Black or African American FEMALE                      17669
                                                                                       MALE                        10680
                                                             Hispanic or Latino        FEMALE                      21465
...                                                                                                                  ...
1                  1               0               [75-91)   Other                     FEMALE                       2729
                                                                                       MALE                         1373
                                                             White                     FEMALE                      22915
                                                                                       MALE                        20211
                                                                                       No matching concept             4

[296 rows x 2 columns]

In [10]:
cohort_names = [
    'ascvd_optum_dod_2019q1_cdm_53'
]
group_variables = ['age_group', 'race_eth', 'gender_concept_name']
outcome_variable = 'ascvd_binary_endpoint_censored'
censored_variable = 'endpoint_censored_binary'
for cohort_name in cohort_names:
    df = db.read_sql_query(query.format(cohort_name=cohort_name))
    print('Cohort Name: {cohort_name}'.format(cohort_name=cohort_name))
    print('Number of patients: {}'.format(df.shape[0]))
    display(df.groupby(['has_statin_history', 'has_cvd_history']).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))
    for group_var in group_variables:
        display(df.groupby(['has_statin_history', 'has_cvd_history', censored_variable, group_var]).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))
    for group_vars in itertools.combinations(group_variables, 2):
        display(df.query('~ascvd_binary_endpoint_censored.isnull()').groupby(['has_statin_history', 'has_cvd_history', censored_variable] + list(group_vars)).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))        
    for group_vars in itertools.combinations(group_variables, 3):
        display(df.query('~ascvd_binary_endpoint_censored.isnull()').groupby(['has_statin_history', 'has_cvd_history', censored_variable] + list(group_vars)).agg(incidence=(outcome_variable, 'mean'), num_patients=(outcome_variable, 'size')))

Cohort Name: ascvd_optum_dod_2019q1_cdm_53
Number of patients: 17774872

                                    incidence  num_patients
has_statin_history has_cvd_history
0                  0                 0.254440      13451151
                   1                 0.780125       2259800
1                  0                 0.585151       1115530
                   1                 0.886679        948391

                                                                       incidence  \
has_statin_history has_cvd_history endpoint_censored_binary age_group
0                  0               0                        [18-30)     0.047193
                                                            [30-45)     0.092995
                                                            [45-55)     0.214036
                                                            [55-65)     0.434104
                                                            [65-75)     0.613835
                                                            [75-91)     0.819272
                   1               0                        [18-30)     0.251911
                                                            [30-45)     0.349088
                                                            [45-55)     0.539825
                                                            [55-65)     0.750553
                                                            [65-75)     0.847889
                                                            [75-91)     0.951866
1                  0               0                        [18-30)     0.123188
                                                            [30-45)     0.214703
                                                            [45-55)     0.347738
                                                            [55-65)     0.549913
                                                            [65-75)     0.670831
                                                            [75-91)     0.821552
                   1               0                        [18-30)     0.512000
                                                            [30-45)     0.592945
                                                            [45-55)     0.704566
                                                            [55-65)     0.839216
                                                            [65-75)     0.890770
                                                            [75-91)     0.956520

                                                                       num_patients
has_statin_history has_cvd_history endpoint_censored_binary age_group
0                  0               0                        [18-30)         3335935
                                                            [30-45)         4840875
                                                            [45-55)         2807974
                                                            [55-65)         1551717
                                                            [65-75)          578367
                                                            [75-91)          336283
                   1               0                        [18-30)          137605
                                                            [30-45)          379771
                                                            [45-55)          447889
                                                            [55-65)          479117
                                                            [65-75)          351406
                                                            [75-91)          464012
1                  0               0                        [18-30)            9077
                                                            [30-45)          147468
                                                            [45-55)          297008
                                                            [55-65)          340663
                                                            [65-75)          204705
                                                            [75-91)          116609
                   1               0                        [18-30)            1616
                                                            [30-45)           41814
                                                            [45-55)          140053
                                                            [55-65)          258838
                                                            [65-75)          246433
                                                            [75-91)          259637

                                                                                       incidence  \
has_statin_history has_cvd_history endpoint_censored_binary race_eth
0                  0               0                        Asian                       0.186847
                                                            Black or African American   0.282131
                                                            Hispanic or Latino          0.235648
                                                            Other                       0.400859
                                                            White                       0.247511
                   1               0                        Asian                       0.702825
                                                            Black or African American   0.779286
                                                            Hispanic or Latino          0.709757
                                                            Other                       0.875433
                                                            White                       0.780644
1                  0               0                        Asian                       0.546613
                                                            Black or African American   0.592569
                                                            Hispanic or Latino          0.598645
                                                            Other                       0.675356
                                                            White                       0.577146
                   1               0                        Asian                       0.861450
                                                            Black or African American   0.887139
                                                            Hispanic or Latino          0.871606
                                                            Other                       0.928684
                                                            White                       0.885699

                                                                                       num_patients
has_statin_history has_cvd_history endpoint_censored_binary race_eth
0                  0               0                        Asian                            494373
                                                            Black or African American       1030987
                                                            Hispanic or Latino              1199953
                                                            Other                           2200795
                                                            White                           8525043
                   1               0                        Asian                             55199
                                                            Black or African American        226561
                                                            Hispanic or Latino               173736
                                                            Other                            283226
                                                            White                           1521078
1                  0               0                        Asian                             36369
                                                            Black or African American         87412
                                                            Hispanic or Latino               113247
                                                            Other                            133378
                                                            White                            745124
                   1               0                        Asian                             21325
                                                            Black or African American         92667
                                                            Hispanic or Latino                83450
                                                            Other                             92513
                                                            White                            658436

                                                                                 incidence  \
has_statin_history has_cvd_history endpoint_censored_binary gender_concept_name
0                  0               0                        FEMALE                0.255826
                                                            MALE                  0.252629
                                                            No matching concept   0.784314
                   1               0                        FEMALE                0.774544
                                                            MALE                  0.786244
                                                            No matching concept   0.963158
1                  0               0                        FEMALE                0.617100
                                                            MALE                  0.548471
                                                            No matching concept   0.918367
                   1               0                        FEMALE                0.894983
                                                            MALE                  0.879016
                                                            No matching concept   0.991379

                                                                                 num_patients
has_statin_history has_cvd_history endpoint_censored_binary gender_concept_name
0                  0               0                        FEMALE                    7544055
                                                            MALE                      5904876
                                                            No matching concept          2220
                   1               0                        FEMALE                    1205480
                                                            MALE                      1053846
                                                            No matching concept           474
1                  0               0                        FEMALE                     547532
                                                            MALE                       567836
                                                            No matching concept           162
                   1               0                        FEMALE                     429134
                                                            MALE                       519074
                                                            No matching concept           183

                                                                                                 incidence  \
has_statin_history has_cvd_history endpoint_censored_binary age_group race_eth
0                  0               0                        [18-30)   Asian                       0.037465
                                                                      Black or African American   0.056541
                                                                      Hispanic or Latino          0.052097
                                                                      Other                       0.119790
                                                                      White                       0.042086
...                                                                                                    ...
1                  1               0                        [75-91)   Asian                       0.942722
                                                                      Black or African American   0.957914
                                                                      Hispanic or Latino          0.943364
                                                                      Other                       0.970204
                                                                      White                       0.957520

                                                                                                 num_patients
has_statin_history has_cvd_history endpoint_censored_binary age_group race_eth
0                  0               0                        [18-30)   Asian                             12278
                                                                      Black or African American         28740
                                                                      Hispanic or Latino                37814
                                                                      Other                             12213
                                                                      White                            239198
...                                                                                                       ...
1                  1               0                        [75-91)   Asian                              4225
                                                                      Black or African American         15991
                                                                      Hispanic or Latino                18451
                                                                      Other                             10572
                                                                      White                            134039

[120 rows x 2 columns]

                                                                                           incidence  \
has_statin_history has_cvd_history endpoint_censored_binary age_group gender_concept_name
0                  0               0                        [18-30)   FEMALE                0.048642
                                                                      MALE                  0.045396
                                                                      No matching concept   0.000000
                                                            [30-45)   FEMALE                0.094958
                                                                      MALE                  0.090671
...                                                                                              ...
1                  1               0                        [65-75)   MALE                  0.897065
                                                                      No matching concept   1.000000
                                                            [75-91)   FEMALE                0.954019
                                                                      MALE                  0.959544
                                                                      No matching concept   1.000000

                                                                                           num_patients
has_statin_history has_cvd_history endpoint_censored_binary age_group gender_concept_name
0                  0               0                        [18-30)   FEMALE                     182825
                                                                      MALE                       147415
                                                                      No matching concept             3
                                                            [30-45)   FEMALE                     353934
                                                                      MALE                       305667
...                                                                                                 ...
1                  1               0                        [65-75)   MALE                        69782
                                                                      No matching concept            36
                                                            [75-91)   FEMALE                     100586
                                                                      MALE                        82658
                                                                      No matching concept            34

[69 rows x 2 columns]

                                                                                                           incidence  \
has_statin_history has_cvd_history endpoint_censored_binary race_eth                  gender_concept_name
0                  0               0                        Asian                     FEMALE                0.179234
                                                                                      MALE                  0.195661
                                                                                      No matching concept   0.666667
                                                            Black or African American FEMALE                0.280873
                                                                                      MALE                  0.283658
                                                                                      No matching concept   0.812500
                                                            Hispanic or Latino        FEMALE                0.234609
                                                                                      MALE                  0.236864
                                                                                      No matching concept   1.000000
                                                            Other                     FEMALE                0.419118
                                                                                      MALE                  0.375788
                                                                                      No matching concept   0.754717
                                                            White                     FEMALE                0.247956
                                                                                      MALE                  0.246905
                                                                                      No matching concept   0.783505
                   1               0                        Asian                     FEMALE                0.698218
                                                                                      MALE                  0.706972
                                                                                      No matching concept   1.000000
                                                            Black or African American FEMALE                0.771812
                                                                                      MALE                  0.789593
                                                                                      No matching concept   0.972973
                                                            Hispanic or Latino        FEMALE                0.698206
                                                                                      MALE                  0.722768
                                                                                      No matching concept   0.800000
                                                            Other                     FEMALE                0.881386
                                                                                      MALE                  0.867522
                                                                                      No matching concept   0.906977
                                                            White                     FEMALE                0.773884
                                                                                      MALE                  0.787744
                                                                                      No matching concept   0.990099
1                  0               0                        Asian                     FEMALE                0.578799
                                                                                      MALE                  0.515264
                                                                                      No matching concept   1.000000
                                                            Black or African American FEMALE                0.617256
                                                                                      MALE                  0.555136
                                                                                      No matching concept   1.000000
                                                            Hispanic or Latino        FEMALE                0.617547
                                                                                      MALE                  0.576260
                                                                                      No matching concept   1.000000
                                                            Other                     FEMALE                0.717535
                                                                                      MALE                  0.621248
                                                                                      No matching concept   0.727273
                                                            White                     FEMALE                0.610869
                                                                                      MALE                  0.539941
                                                                                      No matching concept   0.958333
                   1               0                        Asian                     FEMALE                0.873472
                                                                                      MALE                  0.851859
                                                                                      No matching concept   1.000000
                                                            Black or African American FEMALE                0.888397
                                                                                      MALE                  0.885331
                                                                                      No matching concept   1.000000
                                                            Hispanic or Latino        FEMALE                0.874543
                                                                                      MALE                  0.868825
                                                                                      No matching concept   1.000000
                                                            Other                     FEMALE                0.939374
                                                                                      MALE                  0.917467
                                                                                      No matching concept   0.961538
                                                            White                     FEMALE                0.895338
                                                                                      MALE                  0.877357
                                                                                      No matching concept   1.000000

                                                                                                           num_patients
has_statin_history has_cvd_history endpoint_censored_binary race_eth                  gender_concept_name
0                  0               0                        Asian                     FEMALE                      37225
                                                                                      MALE                        31989
                                                                                      No matching concept             3
                                                            Black or African American FEMALE                     104460
                                                                                      MALE                        69351
                                                                                      No matching concept            48
                                                            Hispanic or Latino        FEMALE                     103828
                                                                                      MALE                        86784
                                                                                      No matching concept             3
                                                            Other                     FEMALE                      52360
                                                                                      MALE                        38881
                                                                                      No matching concept            53
                                                            White                     FEMALE                     776582
                                                                                      MALE                       655134
                                                                                      No matching concept            97
                   1               0                        Asian                     FEMALE                       8082
                                                                                      MALE                         8692
                                                                                      No matching concept             4
                                                            Black or African American FEMALE                      49433
                                                                                      MALE                        35151
                                                                                      No matching concept            37
                                                            Hispanic or Latino        FEMALE                      30428
                                                                                      MALE                        26981
                                                                                      No matching concept             5
                                                            Other                     FEMALE                      30536
                                                                                      MALE                        23151
                                                                                      No matching concept            43
                                                            White                     FEMALE                     284792
                                                                                      MALE                       268162
                                                                                      No matching concept           101
1                  0               0                        Asian                     FEMALE                       3896
                                                                                      MALE                         4029
                                                                                      No matching concept             2
                                                            Black or African American FEMALE                      13074
                                                                                      MALE                         8742
                                                                                      No matching concept            11
                                                            Hispanic or Latino        FEMALE                      16470
                                                                                      MALE                        13926
                                                                                      No matching concept             1
                                                            Other                     FEMALE                       7123
                                                                                      MALE                         5563
                                                                                      No matching concept            11
                                                            White                     FEMALE                      92370
                                                                                      MALE                        83974
                                                                                      No matching concept            24
                   1               0                        Asian                     FEMALE                       4173
                                                                                      MALE                         5245
                                                                                      No matching concept             1
                                                            Black or African American FEMALE                      25958
                                                                                      MALE                        19988
                                                                                      No matching concept            31
                                                            Hispanic or Latino        FEMALE                      19975
                                                                                      MALE                        21132
                                                                                      No matching concept             1
                                                            Other                     FEMALE                      13905
                                                                                      MALE                        13328
                                                                                      No matching concept            26
                                                            White                     FEMALE                     145803
                                                                                      MALE                       169272
                                                                                      No matching concept            57

                                                                                                                     incidence  \
has_statin_history has_cvd_history endpoint_censored_binary age_group race_eth                  gender_concept_name
0                  0               0                        [18-30)   Asian                     FEMALE                0.036131
                                                                                                MALE                  0.039253
                                                                      Black or African American FEMALE                0.058995
                                                                                                MALE                  0.052530
                                                                      Hispanic or Latino        FEMALE                0.053653
...                                                                                                                        ...
1                  1               0                        [75-91)   Other                     MALE                  0.968387
                                                                                                No matching concept   1.000000
                                                                      White                     FEMALE                0.954868
                                                                                                MALE                  0.960544
                                                                                                No matching concept   1.000000

                                                                                                                     num_patients
has_statin_history has_cvd_history endpoint_censored_binary age_group race_eth                  gender_concept_name
0                  0               0                        [18-30)   Asian                     FEMALE                       7030
                                                                                                MALE                         5248
                                                                      Black or African American FEMALE                      17832
                                                                                                MALE                        10908
                                                                      Hispanic or Latino        FEMALE                      21695
...                                                                                                                           ...
1                  1               0                        [75-91)   Other                     MALE                         3701
                                                                                                No matching concept             8
                                                                      White                     FEMALE                      71524
                                                                                                MALE                        62500
                                                                                                No matching concept            15

[314 rows x 2 columns]